* image scanner
** (foo img start-poen end-poen)
** citibank
*** y 701 797 893 dy=96
*** x 31 89  dx=58
* "1234" zu tastatur
** (postion #\a fmap) => 20
** (wo 20) => (x y)


* ZU MACHEN
** DONE touch point kalibration
** DONE pixel-position via cons od. list
** DONE swipe
** TODO ACTIVATOR MACRO
** TODO -mode.el richtig hinzufuegen 
** TODO record system
** TODO opticl
** TODO keyboard zu swipe, pgdn/pgup
** TODO in qt-wrapper disable the mark set feature

* HISTORY
** eigentlich wollte ich alle prozess automatisch zu machen. d.h. wenn man wie machine arbeitet, dann kommt geld. so das system ist es. Dann, mache ich eine machine dafuer via computer program. dann mann kann nur das system benutzen, ohne die physikalische, zeitliche arbeiten. so kommt die AI? k.a. aber, diese arbeit wird die zsene zeigen. Wie kann man xs
** was bedeute die automatische maschine, A.I., Roboten, usw.? man sagt, wegen die ai roboten koentten die leute die arbeit verloren. 
  
* SYNOPSIS
** (init)
*** (fit-again)
** 

* SIZE
** (1136 640)
** (1280 758)
** (1220 724)
** (888 537)
** (706 434)

* ACHTUNG
** erstmal (qt-run) dann (connect)?
*** iphn mode change, than disconnect, deswegen

* MEMO

(defun mouse-start-rectangle (start-event)
  (interactive "e")
  (deactivate-mark)
  (mouse-set-point start-event)
  (rectangle-mark-mode +1)
  (let ((drag-event))
    (track-mouse
      (while (progn
               (setq drag-event (read-event))
               (mouse-movement-p drag-event))
        (mouse-set-point drag-event)))))

(global-set-key (kbd "S-<down-mouse-1>") #'mouse-start-rectangle)


(defun mouse-start-rectangle (start-event)                        
  (interactive "e")                                               
  (deactivate-mark)                                               
  (mouse-set-point start-event)                                   
  ;; (rectangle-mark-mode +1)
  (message "%s" (mouse-pixel-position))

  (let ((drag-event))                                             
    (track-mouse                                                  
      (while (progn                                               
	       (setq drag-event (read-event))                     
	       (mouse-movement-p drag-event))                     
	(mouse-set-point drag-event)
	(message "%s" (mouse-pixel-position))))))


